name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate: [planager-data, planager-parser, planager-cli]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build -p ${{ matrix.crate }} --verbose

      - name: Test
        run: cargo test -p ${{ matrix.crate }} --verbose